<project name="test" default="run">
    <target name="run">
        <javac srcdir="." destdir="." includeantruntime="false">
            <classpath>
                <pathelement path="/home/kanekira/.m2/repository/org/springframework/security/spring-security-crypto/6.5.2/spring-security-crypto-6.5.2.jar"/>
                <pathelement path="/home/kanekira/.m2/repository/org/apache/commons/commons-logging/1.3.4/commons-logging-1.3.4.jar"/>
            </classpath>
        </javac>
        <java classname="test_bcrypt" fork="true">
            <classpath>
                <pathelement location="."/>
                <pathelement path="/home/kanekira/.m2/repository/org/springframework/security/spring-security-crypto/6.5.2/spring-security-crypto-6.5.2.jar"/>
                <pathelement path="/home/kanekira/.m2/repository/org/apache/commons/commons-logging/1.3.4/commons-logging-1.3.4.jar"/>
            </classpath>
        </java>
    </target>
</project>
